COLUMN_LABELS = {
    "id": "ID",
    "guest_id": "ID гостя",
    "phone": "Номер телефона",
    "mac": "MAC-адрес",
    "ip": "IP-адрес",
    "nas_id": "Устройство доступа",
    "hotel": "Объект",
    "ssid": "Wi-Fi сеть",
    "vlan_id": "VLAN",
    "event_type": "Событие",
    "event_time": "Время события",
    "details": "Описание",
    "created_at": "Создано",
    "updated_at": "Обновлено",
    "first_verified_at": "Первая верификация",
    "first_hotel": "Первый объект",
    "auth_method": "Метод авторизации",
    "status": "Статус",
    "started_at": "Начало сессии",
    "ended_at": "Конец сессии",
    "expires_at": "Действует до",
    "callerid_raw": "CallerID",
    "source_ip": "IP источника",
    "result": "Результат",
    "hotel_name": "Объект",
    "ssid_name": "Wi-Fi сеть",
    "subnet_cidr": "Подсеть",
    "mikrotik_interface": "Интерфейс MikroTik",
    "hotspot_server": "Hotspot server",
    "is_active": "Активна",
    "acct_session_id": "ID RADIUS-сессии",
    "last_seen_at": "Последняя активность",
    "terminate_cause": "Причина завершения",
    "acct_session_time": "Длительность, сек",
    "last_auth_at": "Последний допуск",
    "device_name": "Имя устройства",
    "first_seen": "Подключено",
    "last_seen": "Последняя активность",
    "room_num": "Номер комнаты",
    "surname": "Фамилия",
    "terminate_cause_raw": "Причина завершения raw",
    }


EVENT_LABELS = {
    "pending_created": "Создана заявка на подтверждение",
    "call_verified": "Номер подтверждён звонком",
    "call_no_pending": "Звонок без активной заявки",
    "call_expired_pending": "Звонок по просроченной заявке",
    "radius_accept_new_session": "Открыта новая сессия",
    "radius_accept_existing_session": "Повторный вход в активную сессию",
    "radius_reject_invalid_phone": "Отклонено: неверный формат номера",
    "radius_reject_pending_waiting_call": "Ожидание звонка",
    "radius_reject_pending_expired": "Отклонено: заявка просрочена",
    "radius_reject_device_limit": "Отклонено: превышен лимит устройств",
    "radius_accept_voucher": "Вход по ваучеру разрешён",
    "radius_reject_voucher": "Вход по ваучеру отклонён",
    "radius_reject_voucher_device_limit": "Отклонено: лимит устройств ваучера",
    "admin_create_voucher": "Создан ваучер",
    "admin_revoke_voucher": "Ваучер отключён",
    "admin_voucher_remove_device": "Устройство освобождено из ваучера",
    "export_requested": "Запрошена выгрузка",
    "export_completed": "Выгрузка готова",
    "export_failed": "Ошибка выгрузки",
    "export_downloaded": "Выгрузка скачана",
}


STATUS_LABELS = {
    "active": "Активна",
    "pending": "Ожидание",
    "verified": "Подтверждена",
    "expired": "Истекла",
    "closed": "Закрыта",
    "blocked": "Заблокирована",
    "revoked": "Отключена",
}

RESULT_LABELS = {
    "matched_pending": "Заявка найдена",
    "no_pending": "Заявка не найдена",
    "expired_pending": "Заявка просрочена",
}


AUTH_METHOD_LABELS = {
    "call": "Звонок",
    "room": "Комната",
    "voucher": "Ваучер",
}


TERMINATE_CAUSE_LABELS = {
    "Lost-Service": "Потеря сервиса",
    "Lost-Carrier": "Потеря линка",
    "Admin-Reset": "Сброс администратором",
    "Session-Timeout": "Истечение времени сессии",
    "Idle-Timeout": "Таймаут неактивности",

    "Legacy-Cleanup": "Автоочистка зависшей сессии",
    "Retest-Cleanup": "Служебное тестовое закрытие",
    "manual_room_test_cleanup": "Служебная очистка тестовой авторизации",
    "stale_session_cleanup": "Автоочистка зависшей сессии",
    "user_request": "Отключено пользователем",

    "lost_service": "Потеря соединения",
    "lost_carrier": "Потеря линка",
    "admin_reset": "Сброс администратором",
    "session_timeout": "Истечение времени сессии",
    "idle_timeout": "Таймаут неактивности",
    "nas_request": "Завершено NAS",
    "nas_reboot": "Перезагрузка NAS",
    "cleanup": "Закрыто служебной очисткой",
    "cleanup_legacy": "Закрыто служебной очисткой",
    "cleanup_retest": "Закрыто служебно",
    "duplicate_session": "Дубликат сессии",
    "interim_timeout": "Нет accounting-обновлений",
    "unknown": "Неизвестная причина",

    "stale_active_cleanup": "Автоочистка старой активной сессии",
    "stale_session_cleanup": "Автоочистка зависшей сессии",
    "duplicate_active_cleanup": "Закрыт дубликат активной сессии",
    "manual_room_test_cleanup": "Служебная очистка тестовой авторизации",
    "user_request": "Отключено пользователем",
    "unknown": "Неизвестная причина",
}
